# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninjas',
            new_name='Ninja',
        ),
    ]
